### ISSUE TITLE
lookup regex accepting

### ISSUE THREAD

**Issue by ghost** [Julian24816/lHelper#30]
`lookup` should accept regex instead of `_` and `%`.

**Comment by Julian24816** [comment]
`_` and `%` are the wildcards used by sqlite3.
using regex would mean loading all cards to memory beforehand.

**Comment by ghost** [comment]
What about http://stackoverflow.com/questions/5071601/how-do-i-use-regex-in-a-sqlite-query ? You can do this in sqlite3...

**Comment by Julian24816** [comment]
implemented in commit b54928c (on branch development)

**Comment by Julian24816** [comment]
recently merged -> available since v1.3.0
