### ISSUE TITLE
Unable to open database file Please contact support.

### ISSUE THREAD

**Issue by ghost** [Julian24816/lHelper#34]
Error message:
`Unable to open database file
Please contact support.`

Steps2repr:
`user /`

Reason:
`/.sqlite3` is an invalid file name; therefore it's not possible for lHelper to create the database

Possible fix:
String escaping?

**Comment by ghost** [comment]
Or just disallow such user names. :)

**Comment by Julian24816** [comment]
fixed in 1.4.2
