### ISSUE TITLE
`use` command may take to long

### ISSUE THREAD

**Issue by ghost** [Julian24816/lHelper#35]
Steps2repr:
`use adeo`

Reason:
lHelper prints out all added cards which may be a lot

**Comment by Julian24816** [comment]
maybe don't print out the added cards?

**Comment by Julian24816** [comment]
this is an unlikely scenario as the user would end up with 1200 added cards after entering the command

**Comment by ghost** [comment]
Then there should be a warning when the user tries to do this with >100 cards...

**Comment by Julian24816** [comment]
added in v1.4.5
