### ISSUE TITLE
lHelper doesn't tell me the solutions anymore when entering a wrong answer

### ISSUE THREAD

**Issue by ghost** [Julian24816/lHelper#46]
![image](https://cloud.githubusercontent.com/assets/20780406/19322691/5954b334-90ba-11e6-87ff-34ccd6195abf.png)

???

**Comment by Julian24816** [comment]
in this case your root forms have been incorrect

**Comment by wigvp** [comment]
But lHelper didn't tell me the correct answer for the meaning!

**Comment by ghost** [comment]
Ah, OK

**Comment by ghost** [comment]
There should be more feedback on correct and not correct answers.
